[2018-11-30 15:32:41,168] [INFO] 账号不存在
[2018-11-30 15:32:41,205] [WARNING] Not Found: /favicon.ico
[2018-11-30 15:32:43,861] [INFO] user object
[2018-11-30 16:03:36,517] [INFO] 账号不存在
[2018-11-30 16:03:39,054] [INFO] user object
[2018-12-01 06:12:52,602] [INFO] user object
[2018-12-01 06:12:59,440] [WARNING] Not Found: /test/app/register/
[2018-12-01 06:13:01,277] [WARNING] Not Found: /test/app/register/
[2018-12-01 06:13:02,020] [WARNING] Not Found: /test/app/register/
[2018-12-01 06:13:03,679] [WARNING] Not Found: /test/app/
[2018-12-01 06:13:04,494] [WARNING] Not Found: /test/
[2018-12-01 06:13:06,504] [WARNING] Not Found: /test/
[2018-12-01 06:13:16,141] [WARNING] Not Found: /test/
[2018-12-01 06:13:16,280] [WARNING] Not Found: /test/
[2018-12-01 06:13:36,398] [WARNING] Not Found: /test/
[2018-12-01 06:13:37,785] [WARNING] Not Found: /test/
[2018-12-01 06:14:23,472] [WARNING] Not Found: /test/
[2018-12-01 06:14:32,415] [WARNING] Not Found: /test/
[2018-12-01 06:18:03,773] [WARNING] Not Found: /test/
[2018-12-01 06:19:14,649] [WARNING] Not Found: /test/
[2018-12-01 06:19:16,991] [WARNING] Not Found: /test/
[2018-12-01 06:19:17,172] [WARNING] Not Found: /test/
[2018-12-01 06:25:08,663] [WARNING] Not Found: /test/
[2018-12-01 06:25:09,653] [WARNING] Not Found: /test/
[2018-12-01 06:25:10,626] [WARNING] Not Found: /test/
[2018-12-01 06:25:11,460] [WARNING] Not Found: /test/
[2018-12-01 06:25:12,174] [WARNING] Not Found: /test/
[2018-12-01 06:25:26,489] [WARNING] Not Found: /test/app/
[2018-12-01 06:25:26,796] [WARNING] Not Found: /test/app/
[2018-12-01 06:25:30,195] [WARNING] Not Found: /test/app/
[2018-12-01 06:25:30,704] [WARNING] Not Found: /test/
[2018-12-01 06:25:31,173] [WARNING] Not Found: /test/app/
[2018-12-01 06:25:32,784] [ERROR] Internal Server Error: /test/asd
Traceback (most recent call last):
  File "/root/.pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/root/.pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: index() takes exactly 1 argument (2 given)
[2018-12-01 06:27:08,758] [WARNING] Not Found: /test/app/
[2018-12-01 06:27:08,939] [WARNING] Not Found: /test/
[2018-12-01 06:27:10,193] [WARNING] Not Found: /test/ads
[2018-12-01 06:27:15,029] [WARNING] Not Found: /test/
[2018-12-01 06:27:15,502] [WARNING] Not Found: /test/
[2018-12-01 06:27:21,891] [WARNING] Not Found: /test/
[2018-12-01 06:27:22,131] [WARNING] Not Found: /test/
[2018-12-01 06:27:30,741] [WARNING] Not Found: /test/app/
[2018-12-01 06:27:30,979] [WARNING] Not Found: /test/admin/
[2018-12-01 06:27:31,671] [WARNING] Not Found: /test/admin/
[2018-12-01 06:27:34,265] [WARNING] Not Found: /test/admin/
[2018-12-01 06:27:34,842] [WARNING] Not Found: /test/app/
[2018-12-01 06:27:35,017] [WARNING] Not Found: /test/
[2018-12-01 06:27:35,332] [WARNING] Not Found: /test/app/
[2018-12-01 06:27:36,064] [WARNING] Not Found: /test/app/
[2018-12-01 07:42:37,914] [WARNING] Not Found: /test/app/
[2018-12-01 07:42:39,473] [WARNING] Not Found: /test/app/
[2018-12-01 07:42:42,094] [WARNING] Not Found: /test/app/
[2018-12-01 07:42:42,666] [WARNING] Not Found: /test/
[2018-12-01 07:42:43,056] [WARNING] Not Found: /test/
[2018-12-01 07:42:51,193] [WARNING] Not Found: /test/app/
[2018-12-01 07:42:51,840] [WARNING] Not Found: /test/app/
[2018-12-01 07:42:56,355] [WARNING] Not Found: /test/app/
[2018-12-01 07:42:57,021] [WARNING] Not Found: /test/
[2018-12-01 07:42:57,425] [WARNING] Not Found: /test/web/
[2018-12-01 07:42:57,868] [WARNING] Not Found: /test/web/
[2018-12-01 07:43:24,570] [WARNING] Not Found: /test/web/
[2018-12-01 07:43:30,310] [WARNING] Not Found: /test/was
[2018-12-01 07:43:36,317] [WARNING] Not Found: /test/wasf
[2018-12-01 07:45:46,351] [WARNING] Not Found: /test/wasf
[2018-12-01 07:45:53,877] [WARNING] Not Found: /test/wasf
[2018-12-01 07:45:54,858] [WARNING] Not Found: /test/app/
[2018-12-01 07:45:55,348] [WARNING] Not Found: /test/app/
[2018-12-01 07:47:37,271] [WARNING] Not Found: /test/app/
[2018-12-01 08:08:13,374] [WARNING] Not Found: /test/app/
[2018-12-01 08:08:14,965] [WARNING] Not Found: /test/app/
[2018-12-01 08:08:18,143] [WARNING] Not Found: /test/
[2018-12-01 08:08:19,717] [WARNING] Not Found: /test/
[2018-12-01 08:08:27,120] [WARNING] Not Found: /test/
[2018-12-01 08:08:27,369] [WARNING] Not Found: /test/
[2018-12-01 08:08:36,811] [WARNING] Not Found: /test/app/
[2018-12-01 08:08:37,054] [WARNING] Not Found: /test/admin/
[2018-12-01 08:08:37,704] [WARNING] Not Found: /test/admin/
[2018-12-01 08:08:43,240] [WARNING] Not Found: /test/admin/app
[2018-12-01 08:08:47,205] [WARNING] Not Found: /test/admin/app
[2018-12-01 08:08:49,755] [WARNING] Not Found: /test/admin/app
[2018-12-01 08:10:22,540] [WARNING] Not Found: /test/admin/app
[2018-12-01 08:26:49,586] [WARNING] Not Found: /test/
[2018-12-01 08:26:52,712] [WARNING] Not Found: /test/
[2018-12-01 08:26:53,155] [WARNING] Not Found: /test/
[2018-12-01 08:26:55,876] [WARNING] Not Found: /test/app/
[2018-12-01 08:26:57,664] [WARNING] Not Found: /test/app/
[2018-12-01 08:27:07,772] [WARNING] Not Found: /test/app/
[2018-12-01 08:28:28,888] [WARNING] Not Found: /test/app/
[2018-12-01 08:28:32,946] [WARNING] Not Found: /test/app/
[2018-12-01 08:28:35,386] [WARNING] Not Found: /test/app
[2018-12-01 08:28:38,349] [WARNING] Not Found: /test/app/
[2018-12-01 08:28:39,061] [WARNING] Not Found: /test/app/register/
[2018-12-01 08:28:39,814] [WARNING] Not Found: /test/app/register/
[2018-12-01 08:28:42,457] [WARNING] Not Found: /test/app/register/
[2018-12-01 08:28:45,985] [WARNING] Not Found: /test/app/register/
[2018-12-01 08:28:51,290] [WARNING] Not Found: /test/app/register/
[2018-12-01 08:28:54,616] [WARNING] Not Found: /test/app/register/
[2018-12-01 08:28:57,063] [WARNING] Not Found: /test/app/register/
[2018-12-01 08:28:59,157] [WARNING] Not Found: /test/app/register/
[2018-12-01 08:29:01,157] [WARNING] Not Found: /test/app/register/
[2018-12-01 08:29:12,009] [WARNING] Not Found: /test/app/register/
[2018-12-01 08:29:16,095] [WARNING] Not Found: /test/app/register/
[2018-12-01 08:29:17,839] [WARNING] Not Found: /test/app/register/
[2018-12-01 08:29:19,852] [WARNING] Not Found: /test/app/register/
[2018-12-01 08:29:21,582] [WARNING] Not Found: /test/app/register/
[2018-12-01 08:29:23,341] [WARNING] Not Found: /test/app/register/
[2018-12-01 08:45:27,996] [WARNING] Not Found: /test/o/app/register
[2018-12-01 08:45:42,978] [INFO] user object
[2018-12-01 08:45:45,418] [INFO] user object
[2018-12-01 08:45:47,435] [INFO] user object
[2018-12-01 08:45:48,300] [INFO] user object
[2018-12-01 08:46:03,681] [WARNING] Not Found: /test/
[2018-12-01 08:52:09,294] [WARNING] Not Found: /test/
[2018-12-01 08:52:15,514] [WARNING] Not Found: /test/s
[2018-12-01 08:52:22,047] [WARNING] Not Found: /test/
[2018-12-01 08:52:23,182] [WARNING] Not Found: /test/
[2018-12-01 08:56:16,600] [WARNING] Not Found: /test/index
[2018-12-01 08:56:19,337] [WARNING] Not Found: /test/index
[2018-12-01 08:58:46,278] [WARNING] Not Found: /test/
[2018-12-01 09:31:00,520] [ERROR] Internal Server Error: /test/index
Traceback (most recent call last):
  File "/root/.pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/root/.pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/.pyenv/versions/2.7.5/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./ftcg/application/default.py", line 9, in index
    return render(request, 'index.html')
  File "/root/.pyenv/versions/2.7.5/lib/python2.7/site-packages/django/shortcuts.py", line 30, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/root/.pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/root/.pyenv/versions/2.7.5/lib/python2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: index.html
